### ISSUE TITLE
Set up infrastructure to automatically build Python wheels

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-python#1]

**Comment by danieldk** [comment]
@sebpuetz

This turns out to be very simple to do for Linux. On Linux, we'd want support for several Python versions on x86_64 (I don't think x86 makes much sense anymore at this point). Also, the Python modules need to be compiled on an ancient Linux version to support older distributions. The [manylinux1](https://www.python.org/dev/peps/pep-0513/) policy specifies CentOS 5 and a set of libraries. Luckily, there is a Docker container for manylinux1, which contains CentOS 5 + all relevant Python versions.

I am documenting the process to build the Linux wheels in this comment, just so that we have the instructions around. We could add this to the README later.

## Enabling docker

On NixOS, add the following to `/etc/nixos/configuration.nix`:

~~~nix
{
  # Enable Docker
  virtualisation.docker.enable = true;

  # Emulate vsyscall emulation, CentOS 5 glibc uses vsyscalls and not vDSO
  boot.kernelParams = [ "vsyscall=emulate" ];

  # Give your user access to the Docker socket.
  users.extraUsers = {
    daniel = {
      # ...
     extraGroups = [ "wheel" "docker" ];
     # ...
    };
  };
}
~~~

And switch to the new system configuration: `sudo nixos-rebuild switch`

## Preparing the Docker container

`pyo3-pack` provides a Docker container, but at this moment it uses Rust stable and we need unstable for `pyo3`. Check out the `pyo3-pack` repo and add the following line to `Dockerfile` after the addition of the musl target:

~~~
&& rustup default nightly-2019-02-07 \
~~~

(Update the date to reflect the installed nightly version. Don't forget to update the MUSL nightly correspondingly.)

Then build a new Docker image:

~~~bash
$ docker build -t pyo3pack .
~~~

## Building wheels

From hereon, it is smooth sailing:

~~~bash
$ docker run --rm -v $(pwd):/io pyo3pack build --release
~~~

When the build is done, you will find the wheels in `target/wheels`. At the moment, it builds for Python 2.7, 3.5, 3.7, and 3.7.

**Comment by sebpuetz** [comment]
Steps for Ubuntu 18.04 (and probably other Debian derivatives):

Follow instructions on https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository to install Docker.

```
$ git clone https://github.com/PyO3/pyo3-pack
$ cd pyo3-pack
```
Change Dockerfile `RUN` to:
```
RUN curl https://www.musl-libc.org/releases/musl-1.1.20.tar.gz -o musl.tar.gz \
    && tar -xzf musl.tar.gz \
    && rm -f musl.tar.gz \
    && cd musl-1.1.20 \
    && ./configure \
    && make install -j2 \
    && cd .. \
    && rm -rf x86_64-unknown-linux-musl \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && rustup toolchain add nightly-2019-02-04 \
    && rustup target add x86_64-unknown-linux-musl \
    && mkdir /io \
    && python3 -m pip install cffi\
    && rustup default nightly-2019-02-04
```

Build image with `$ docker build -t pyo3pack`

CD to Cargo project with bindings.

Build wheels with `$ docker run --rm -v $(pwd):/io pyo3pack build --release`, finally find wheels at `target/wheels/`

**Comment by danieldk** [comment]
Since we have this set up and figured out for Windows and Linux, I will close this issue for now. In the future, we could upload to PyPI automatically, but let's keep ourselves in the loop.
