### ISSUE TITLE
3.5 and 3.6 wheels for macOS

### ISSUE THREAD

**Issue by twuebi** [finalfusion/finalfusion-python#10]
Just stumbled over this. Could we also have a wheel for python 3.6 and 3.5 on macOS?

**Comment by sebpuetz** [comment]
[Seems to be possible?](https://pyo3.rs/v0.7.0/building_and_distribution.html)

>Python version
>
>PyO3 uses a build script to determine the Python version and set the correct linker arguments. By
default it uses the python3 executable. You can override the Python interpreter by setting
PYTHON_SYS_EXECUTABLE, e.g., PYTHON_SYS_EXECUTABLE=python3.6.

**Comment by danieldk** [comment]
@twuebi There is no Python 3.5 and 3.6 in macOS Mojave? What's the use case? Older macOS versions? If we want to provide older wheels, then they should be compiled on older macOSes as well (for ABI compat). I'll check if we can do automated builds via Travis-CI.

@sebpuetz You typically don't have to set these variables. Most systems have executables python[x].[y] with minor versions and `pyo3-pack` compiles modules for every such interpreter on the path. For example:

~~~bash
$ pyo3-pack build --release
🔗 Found pyo3 bindings
🐍 Found Python 2.7mu at python2.7, Python 3.5m at python3.5, Python 3.6m at python3.6, Python 3.7m at python3.7
[…]
📦 Built wheel for python 2.7mu to /home/daniel/git/finalfusion-python/target/wheels/finalfusion-0.2.0-cp27-cp27mu-manylinux1_x86_64.whl
📦 Built wheel for python 3.5m to /home/daniel/git/finalfusion-python/target/wheels/finalfusion-0.2.0-cp35-cp35m-manylinux1_x86_64.whl
📦 Built wheel for python 3.6m to /home/daniel/git/finalfusion-python/target/wheels/finalfusion-0.2.0-cp36-cp36m-manylinux1_x86_64.whl
📦 Built wheel for python 3.7m to /home/daniel/git/finalfusion-python/target/wheels/finalfusion-0.2.0-cp37-cp37m-manylinux1_x86_64.whl
~~~

**Comment by twuebi** [comment]
On mac, I was on python 3.5 through pyenv, so no specific use case, just the python version I was using. Switched to 3.7 now, so if my use case is a fringe case anyway, it shouldn't be too important.

**Comment by danieldk** [comment]
Ack. I'll try and see if we can do automated builds on High Sierra.

**Comment by danieldk** [comment]
CI builds on macOS 10.13 give us 3.6:
https://github.com/finalfusion/finalfusion-python/releases/tag/test

It's a shame that Homebrew doesn't ship older snakes anymore. I'll upload the wheel for 3.6 later.

**Comment by twuebi** [comment]
It seems we lost the 3.7 wheel for macOS.

**Comment by danieldk** [comment]
On Thu, Jun 13, 2019, at 13:02, Tobias Pütz wrote:
> It seems we lost the 3.7 wheel.

We didn't lose it ;). I have to manually build and upload it.

**Comment by twuebi** [comment]
> On Thu, Jun 13, 2019, at 13:02, Tobias Pütz wrote: It seems we lost the 3.7 wheel.
> We didn't lose it ;). I have to manually build and upload it.

Ah, I see. I was confused because 0.3 for 3.6 was there.
