### ISSUE TITLE
Batched embedding lookup

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-python#102]
Individual lookups for quantized embeddings are extremely slow, batched lookups are a lot faster.

**Comment by danieldk** [comment]
It's especially the projection that makes them expensive. This could indeed provide a nice speedup, also in ff-rust, especially for unknowns.

**Comment by sebpuetz** [comment]
We're already doing batched lookups in the `Storage` implementations, I don't see a clean solution for moving this to the `Embeddings` level. `Vocab.idx` can return any of  `int`, `List[int]` and `None`, we'd have to flatten the lists, find a solution for `None`s, sum the segments according to the list lengths and there's probably more issues that I didn't think about.

Adding batched lookups was mostly motivated by the extremely slow dequantization, but since you yesterday pointed out that this is due to borked threading in OpenBLAS, the motivation for adding batched lookups is gone.

Closing for now!
