### ISSUE TITLE
Use of locale analogy integration test

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-python#118]
I think I missed this during reviewing, but the analogy integration test has:

```
export LC_ALL=en_US.UTF-8
```

This fails in two cases:

* Sandboxed builds, in which glibc locales are typically not available.
* People who have systems without this locale installed (e.g. because they use some non-English locale).

@sebpuetz Do you encounter problems when e.g. using `export LC_ALL=C`? (Which should avoid doing any parsing of character data.)

**Comment by sebpuetz** [comment]
Oops, I forgot to delete that line. That was one instance of poking around in CI configs & scripts. I'll fix it. I was just about to publish the draft release to pypi, close call!
