### ISSUE TITLE
Restrict AppVeyor Builds to Pullrequests and Releases

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-python#17]
I think AppVeyor is processing the builds sequentially, this takes a lot of time. We are currently building on both CI services when something is pushed to a branch and also when a PR is made.

Maybe we can restrict the AppVeyor builds to pull requests and releases? I'm not sure how release builds are triggered, so I don't know if this is actually doable.

**Comment by danieldk** [comment]
Release builds are triggered on tags.

**Comment by danieldk** [comment]
I have changed the AppVeyor configuration to only build on tags. It's mostly there anyway to get wheels for Windows. This changes the release procedure a bit, we should do a dummy tag to see if Windows builds still work before actually tagging a release.
