### ISSUE TITLE
Increase PyPI bus factor

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-python#18]
@sebpuetz @twuebi

If you want, I can also add you to the PyPI finalfusion account. Increases the bus factor by 2. But I'd need your PyPI handles.

**Comment by sebpuetz** [comment]
Didn't know that bus factor was a thing. I just registered on PyPI, my handle is sebptz

**Comment by twuebi** [comment]
mine's [tobias.p](https://pypi.org/user/tobias.p/)

**Comment by danieldk** [comment]
Thanks! Added.
