### ISSUE TITLE
Expose model parameters

### ISSUE THREAD

**Issue by shadeMe** [finalfusion/finalfusion-python#2]
The interface could use getters for the various model parameters specified [here](https://github.com/danieldk/finalfrontier/blob/master/man/ff-format.5.md), particularly the commonly used ones such as dimension, vocab size, context size, etc.

**Comment by danieldk** [comment]
That would indeed be very useful. There will be some very large changes to this crate. @sebpuetz & I have made a new, generic, embedding format (*finalfusion*) that supports regular word embeddings, subword units, memory mapping, and quantized embedding matrices. This work has all been done in the danieldk/rust2vec repository.

finalfrontier will directly create finalfusion embeddings in the future and now already supports conversion to the finalfusion format in the `master` branch. This crate will change from being a binding finalfrontier to binding rust2vec.

The finalfusion format has a TOML metadata chunk that can expose hyperparameters. The TOML data can already be retrieved and changed from Python (see the `rust2vec-python` branch). We are currently wrapping up changes in rust2vec to release version 0.5.0, which has all these changes. This project will then be migrated and renamed soon thereafter.

**Comment by danieldk** [comment]
It is now possible to get metadata. Example:

https://github.com/danieldk/finalfusion-python/blob/ac9ac502a9b0fb159f303f6e49d0d3d306ed65ea/examples/print-metadata.py

Thanks for the suggestion!
