### ISSUE TITLE
Release 0.4 branch

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-python#37]
I would like to branch a new a new release. Primarily to ensure that we are in sync with finalfusion, to get analogy queries with masking, and it is nice to have the norms functionality as well.

@sebpuetz : do you want to get #32 in before the release?

**Comment by sebpuetz** [comment]
> @sebpuetz : do you want to get #32 in before the release?

Sure, I'll do that today

**Comment by sebpuetz** [comment]
I opened the PR for implementing `PyMappingProtocol`. After that, there's one more fix in the pipeline, namely fixing the analogy unit tests by explicitly `pytest.fail()`ing those.

**Comment by danieldk** [comment]
@sebpuetz  The `fail` fixes are not necessary anymore, I am now preparing a PR that cleans up all tests and makes these changes as well.

**Comment by danieldk** [comment]
See #40

**Comment by danieldk** [comment]
Ok, looks like we are good to go!
