### ISSUE TITLE
Numpy dependency should be specified

### ISSUE THREAD

**Issue by Stigjb** [finalfusion/finalfusion-python#85]
If you try to get an embedding without having Numpy installed in the Python environment, you get a panic. Is it possible to have Numpy be automatically installed as a dependency when you run `pip install finalfusion`?

**Comment by danieldk** [comment]
I have to check if anything changed, but before it was not possible to specify such dependencies with `pyo3-pack`/`maturin`.

**Comment by danieldk** [comment]
Ah, seems that this is now possible, I'll do a PR.

**Comment by Stigjb** [comment]
That was quick, thank you!
