### ISSUE TITLE
Consider replacing finalfusion-python by ffp?

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-python#87]
Just wanted to have your opinion on this @sebpuetz . I think my objection at the time is that we had to keep two implementations (Rust, Python) in sync. But:

* finalfusion is mostly 'done' (API stable, data format stable), so having two implementations is less of an issue now.
* In the meanwhile, we have seen cases of unsoundness in pyo3.

**Comment by sebpuetz** [comment]
I'd be fine with that, `ffp` should be equal now in terms of supported chunks and formats. There's no support for similarity and analogy queries so far, but that wouldn't be hard to add.

There's documentation for all classes and methods, but not all of it might be up to the standard that we want to provide. Something similar could probably be said about test coverage - most is tested, but I'm not sure wrt. how thorough it is.

So I think it'd be sensible if the code would be moved to a new repo in the `finalfusion` org for which I'd go over my existing code, fix up documentation, tests and possible mistakes before opening PRs. @twuebi reviewed some PRs for my repo but most of the code was just written by myself.

Does this sound good to you or do you prefer skipping the PR part and just rely on me reviewing my own code?

__edit:__ `ffp` is the first Python package I wrote & published, so a good part of it was learning-by-doing. For instance, there's a lot of `struct.unpack("<Q", file.read(8))` but at some points it's `struct.unpack("<Q", file.read(struct.calcsize("<Q")))` and i should probably settle for one of the two formulations.

**Comment by danieldk** [comment]
> So I think it'd be sensible if the code would be moved to a new repo in the `finalfusion` org for which I'd go over my existing code, fix up documentation, tests and possible mistakes before opening PRs. @twuebi reviewed some PRs for my repo but most of the code was just written by myself.

Sounds good! If it is not too much work for you. I'd be fine reviewing the PRs.

I think it would be cool if it could eventually replace finalfusion on pypi, so that people could just do `pip install finalfusion`.

**Comment by danieldk** [comment]
Fixed.
